version: '3.8'

services:
  envoy:
    build: .
    container_name: gbros-envoy
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

